// Generated by @wagmi/cli@1.3.0 on 7/19/2023 at 8:49:32 PM
import {
  useNetwork,
  useContractRead,
  UseContractReadConfig,
  useContractWrite,
  Address,
  UseContractWriteConfig,
  usePrepareContractWrite,
  UsePrepareContractWriteConfig,
} from 'wagmi'
import {
  ReadContractResult,
  WriteContractMode,
  PrepareWriteContractResult,
} from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Greeter
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * - [__View Contract on Zk Sync Era Testnet Zk Explorer__](https://goerli.explorer.zksync.io/address/0x82fcf733eaf7ac0691c99e39d487ffa5b5e5d42d)
 * -
 */
export const greeterABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [{ name: '_greeting', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'greet',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_greeting', internalType: 'string', type: 'string' }],
    name: 'setGreeting',
    outputs: [],
  },
] as const

/**
 * - [__View Contract on Zk Sync Era Testnet Zk Explorer__](https://goerli.explorer.zksync.io/address/0x82fcf733eaf7ac0691c99e39d487ffa5b5e5d42d)
 * -
 */
export const greeterAddress = {
  280: '0x82FCF733EaF7ac0691C99E39D487ffa5b5E5d42d',
  31337: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
} as const

/**
 * - [__View Contract on Zk Sync Era Testnet Zk Explorer__](https://goerli.explorer.zksync.io/address/0x82fcf733eaf7ac0691c99e39d487ffa5b5e5d42d)
 * -
 */
export const greeterConfig = {
  address: greeterAddress,
  abi: greeterABI,
} as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link greeterABI}__.
 *
 * - [__View Contract on Zk Sync Era Testnet Zk Explorer__](https://goerli.explorer.zksync.io/address/0x82fcf733eaf7ac0691c99e39d487ffa5b5e5d42d)
 * -
 */
export function useGreeterRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof greeterABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof greeterABI, TFunctionName, TSelectData>,
    'abi' | 'address'
  > & { chainId?: keyof typeof greeterAddress } = {} as any,
) {
  const { chain } = useNetwork()
  const chainId = config.chainId ?? chain?.id
  return useContractRead({
    abi: greeterABI,
    address: greeterAddress[chainId as keyof typeof greeterAddress],
    ...config,
  } as UseContractReadConfig<typeof greeterABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link greeterABI}__ and `functionName` set to `"greet"`.
 *
 * - [__View Contract on Zk Sync Era Testnet Zk Explorer__](https://goerli.explorer.zksync.io/address/0x82fcf733eaf7ac0691c99e39d487ffa5b5e5d42d)
 * -
 */
export function useGreeterGreet<
  TFunctionName extends 'greet',
  TSelectData = ReadContractResult<typeof greeterABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof greeterABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof greeterAddress } = {} as any,
) {
  const { chain } = useNetwork()
  const chainId = config.chainId ?? chain?.id
  return useContractRead({
    abi: greeterABI,
    address: greeterAddress[chainId as keyof typeof greeterAddress],
    functionName: 'greet',
    ...config,
  } as UseContractReadConfig<typeof greeterABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link greeterABI}__.
 *
 * - [__View Contract on Zk Sync Era Testnet Zk Explorer__](https://goerli.explorer.zksync.io/address/0x82fcf733eaf7ac0691c99e39d487ffa5b5e5d42d)
 * -
 */
export function useGreeterWrite<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined,
  TChainId extends number = keyof typeof greeterAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof greeterABI, string>['request']['abi'],
        TFunctionName,
        TMode
      > & { address?: Address; chainId?: TChainId }
    : UseContractWriteConfig<typeof greeterABI, TFunctionName, TMode> & {
        abi?: never
        address?: never
        chainId?: TChainId
      } = {} as any,
) {
  const { chain } = useNetwork()
  const chainId = config.chainId ?? chain?.id
  return useContractWrite<typeof greeterABI, TFunctionName, TMode>({
    abi: greeterABI,
    address: greeterAddress[chainId as keyof typeof greeterAddress],
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link greeterABI}__ and `functionName` set to `"setGreeting"`.
 *
 * - [__View Contract on Zk Sync Era Testnet Zk Explorer__](https://goerli.explorer.zksync.io/address/0x82fcf733eaf7ac0691c99e39d487ffa5b5e5d42d)
 * -
 */
export function useGreeterSetGreeting<
  TMode extends WriteContractMode = undefined,
  TChainId extends number = keyof typeof greeterAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof greeterABI,
          'setGreeting'
        >['request']['abi'],
        'setGreeting',
        TMode
      > & {
        address?: Address
        chainId?: TChainId
        functionName?: 'setGreeting'
      }
    : UseContractWriteConfig<typeof greeterABI, 'setGreeting', TMode> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'setGreeting'
      } = {} as any,
) {
  const { chain } = useNetwork()
  const chainId = config.chainId ?? chain?.id
  return useContractWrite<typeof greeterABI, 'setGreeting', TMode>({
    abi: greeterABI,
    address: greeterAddress[chainId as keyof typeof greeterAddress],
    functionName: 'setGreeting',
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link greeterABI}__.
 *
 * - [__View Contract on Zk Sync Era Testnet Zk Explorer__](https://goerli.explorer.zksync.io/address/0x82fcf733eaf7ac0691c99e39d487ffa5b5e5d42d)
 * -
 */
export function usePrepareGreeterWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof greeterABI, TFunctionName>,
    'abi' | 'address'
  > & { chainId?: keyof typeof greeterAddress } = {} as any,
) {
  const { chain } = useNetwork()
  const chainId = config.chainId ?? chain?.id
  return usePrepareContractWrite({
    abi: greeterABI,
    address: greeterAddress[chainId as keyof typeof greeterAddress],
    ...config,
  } as UsePrepareContractWriteConfig<typeof greeterABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link greeterABI}__ and `functionName` set to `"setGreeting"`.
 *
 * - [__View Contract on Zk Sync Era Testnet Zk Explorer__](https://goerli.explorer.zksync.io/address/0x82fcf733eaf7ac0691c99e39d487ffa5b5e5d42d)
 * -
 */
export function usePrepareGreeterSetGreeting(
  config: Omit<
    UsePrepareContractWriteConfig<typeof greeterABI, 'setGreeting'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof greeterAddress } = {} as any,
) {
  const { chain } = useNetwork()
  const chainId = config.chainId ?? chain?.id
  return usePrepareContractWrite({
    abi: greeterABI,
    address: greeterAddress[chainId as keyof typeof greeterAddress],
    functionName: 'setGreeting',
    ...config,
  } as UsePrepareContractWriteConfig<typeof greeterABI, 'setGreeting'>)
}
