// Generated by @wagmi/cli@1.3.0 on 7/17/2023 at 6:58:08 PM
import {
  useContractRead,
  UseContractReadConfig,
  useContractWrite,
  UseContractWriteConfig,
  usePrepareContractWrite,
  UsePrepareContractWriteConfig,
} from 'wagmi'
import {
  ReadContractResult,
  WriteContractMode,
  PrepareWriteContractResult,
} from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Greeter
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const greeterABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [{ name: '_greeting', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'greet',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_greeting', internalType: 'string', type: 'string' }],
    name: 'setGreeting',
    outputs: [],
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link greeterABI}__.
 */
export function useGreeterRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof greeterABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof greeterABI, TFunctionName, TSelectData>,
    'abi'
  > = {} as any,
) {
  return useContractRead({
    abi: greeterABI,
    ...config,
  } as UseContractReadConfig<typeof greeterABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link greeterABI}__ and `functionName` set to `"greet"`.
 */
export function useGreeterGreet<
  TFunctionName extends 'greet',
  TSelectData = ReadContractResult<typeof greeterABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof greeterABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: greeterABI,
    functionName: 'greet',
    ...config,
  } as UseContractReadConfig<typeof greeterABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link greeterABI}__.
 */
export function useGreeterWrite<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof greeterABI, string>['request']['abi'],
        TFunctionName,
        TMode
      >
    : UseContractWriteConfig<typeof greeterABI, TFunctionName, TMode> & {
        abi?: never
      } = {} as any,
) {
  return useContractWrite<typeof greeterABI, TFunctionName, TMode>({
    abi: greeterABI,
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link greeterABI}__ and `functionName` set to `"setGreeting"`.
 */
export function useGreeterSetGreeting<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof greeterABI,
          'setGreeting'
        >['request']['abi'],
        'setGreeting',
        TMode
      > & { functionName?: 'setGreeting' }
    : UseContractWriteConfig<typeof greeterABI, 'setGreeting', TMode> & {
        abi?: never
        functionName?: 'setGreeting'
      } = {} as any,
) {
  return useContractWrite<typeof greeterABI, 'setGreeting', TMode>({
    abi: greeterABI,
    functionName: 'setGreeting',
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link greeterABI}__.
 */
export function usePrepareGreeterWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof greeterABI, TFunctionName>,
    'abi'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: greeterABI,
    ...config,
  } as UsePrepareContractWriteConfig<typeof greeterABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link greeterABI}__ and `functionName` set to `"setGreeting"`.
 */
export function usePrepareGreeterSetGreeting(
  config: Omit<
    UsePrepareContractWriteConfig<typeof greeterABI, 'setGreeting'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: greeterABI,
    functionName: 'setGreeting',
    ...config,
  } as UsePrepareContractWriteConfig<typeof greeterABI, 'setGreeting'>)
}
